version: '3.3'

services:
  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: hackernews-super-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            host: db
            port: 3306
            user: root
            password: pwd4mysql!
            migrations: true

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: hackernews
      MYSQL_PASSWORD: pwd4hackernews!
      MYSQL_ROOT_PASSWORD: pwd4mysql!
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: